In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

<B>NUMPY ARRAYS

<b> One dimensional array

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

<b> Array attributes

<b>Array type check

In [3]:
a.dtype

dtype('int32')

In [4]:
a.ndim

1

In [5]:
a.shape

(9,)

In [6]:
a.size

9

<b>Multi dimensional array

In [8]:
d2_array = np.array([[1,2,3,4,5],[4,5,6,7,8]])
d2_array

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [9]:
d2_array.size

10

In [10]:
d2_array.shape

(2, 5)

In [11]:
d2_array.ndim

2

In [12]:
a= np.array([[1,2],[1,4]])

In [13]:
a.ndim

2

In [14]:
a.size

4

In [15]:
a[0][1]

2

In [16]:
array_2d = np.array([[[1,2,3,]]])

In [17]:
array_2d.dtype

dtype('int32')

In [18]:
array_2d.ndim

3

In [19]:
b = np.array([[[1,2],[3,4],[5,6],[7,8]]])

In [20]:
b.ndim

3

In [21]:
b.size

8

In [22]:
b.shape

(1, 4, 2)

In [23]:
b[0][1][1]

4

Changing datatype of an array

In [24]:
c = np.array([[[1,2,3,4,5],
       [6,7,8,9,10],
       [11,12,13,14,15]]] , float)
c

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.]]])

In [25]:
c.size

15

In [26]:
c.ndim

3

In [27]:
c.shape

(1, 3, 5)

In [28]:
c[0]

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

<b>Big size array

In [29]:
big_array = np.array([[
                       [1,2,3],[4,5,6],[7,8,9]],
                      [
                       [10,11,12],[13,14,15],[16,17,18]],
                      [
                       [19,20,21],[22,23,24],[25,26,27]]
                    ])

In [30]:
big_array

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [31]:
big_array.dtype

dtype('int32')

In [32]:
big_array.ndim

3

In [33]:
big_array.size

27

In [34]:
big_array.shape

(3, 3, 3)

<b> Filling Arrays

In [35]:
arr = np.full((3,3,4),6)

In [36]:
arr

array([[[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]],

       [[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]],

       [[6, 6, 6, 6],
        [6, 6, 6, 6],
        [6, 6, 6, 6]]])

<b>Filling Zeroes and Ones

In [37]:
a = np.zeros((3,3), dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [38]:
a = np.ones((3,4,4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [39]:
a.ndim

3

<b>Empty and random

In [40]:
na= np.empty((2,3))

In [97]:
na

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
ran_array = np.random.random((3,2,1))

In [43]:
ran_array

array([[[0.15974447],
        [0.32828393]],

       [[0.27749006],
        [0.39887375]],

       [[0.63292496],
        [0.64615407]]])

In [44]:
ran_array.ndim

3

In [45]:
ran_array.size

6

In [46]:
ran_array.shape

(3, 2, 1)

<b>Filling within a range

<b> FIlling using Arange

In [92]:
a =np.arange(10,100,5)

In [85]:
a

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [86]:
a.ndim

1

<b> Filling using linspace

In [93]:
b = np.linspace(20,80,11 , dtype =int)
b

array([20, 26, 32, 38, 44, 50, 56, 62, 68, 74, 80])

In [61]:
a =np.array([[4,9],[25,100],[16,81]])

In [94]:
a.ndim

1

In [62]:
np.exp(a)

array([[5.45981500e+01, 8.10308393e+03],
       [7.20048993e+10, 2.68811714e+43],
       [8.88611052e+06, 1.50609731e+35]])

In [63]:
np.sqrt(a)

array([[ 2.,  3.],
       [ 5., 10.],
       [ 4.,  9.]])

In [65]:
np.sum(a)

235

In [66]:
np.log(a)

array([[1.38629436, 2.19722458],
       [3.21887582, 4.60517019],
       [2.77258872, 4.39444915]])

In [67]:
np.sin(a)

array([[-0.7568025 ,  0.41211849],
       [-0.13235175, -0.50636564],
       [-0.28790332, -0.62988799]])

In [68]:
np.cos(a)

array([[-0.65364362, -0.91113026],
       [ 0.99120281,  0.86231887],
       [-0.95765948,  0.77668598]])

In [69]:
np.tan(a)

array([[ 1.15782128, -0.45231566],
       [-0.13352641, -0.58721392],
       [ 0.30063224, -0.81099442]])

In [70]:
np.angle(a)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [71]:
np.amax(a)

100

In [74]:
np.amin(a)

4

In [78]:
np.mean(a)

39.166666666666664

In [82]:
np.median(a)

20.5

In [95]:
np.set_printoptions(suppress=True)